In [25]:
from bs4 import BeautifulSoup
import pandas as pd
import requests
import warnings
import csv
from sklearn.preprocessing import MultiLabelBinarizer

warnings.filterwarnings('ignore')
pd.set_option("display.max_rows", None)

In [26]:
url = "https://fbref.com/en/comps/Big5/stats/players/Big-5-European-Leagues-Stats"
html = requests.get(url=url).text

soup = BeautifulSoup(html, "html.parser")
table = soup.find("tbody")
rows = table.find_all("tr")

cols = ['player_id', 'name', 'country', 'position', 'club', 'league', 'games_played',\
       'games_started', 'minutes_played', 'minutes_per_90', 'goals', 'assists',\
       'non_penalty_goals', 'penalty_goals', 'penalty_attempted', 'yellow_cards',\
       'red_card', 'goals_per_90', 'assits_per_90', 'non_penalty_goals_per_90']

In [27]:
df = pd.DataFrame(columns=cols)

for row in rows:
    try:
        if row['class']:
            continue
    except:
        player_id = int(row.find("th").text)
        values = row.find_all("td")
        name = values[0].find('a').text
        country = values[1].text.split(' ')[len(values[1].text.split(' ')) - 1]
        position = values[2].text.split(',')
        club = values[3].text
        league = values[4].find('a').text
        games_played = int(values[7].text)
        games_started = int(values[8].text)
        minutes_played = int(''.join(values[9].text.split(',')))
        minutes_per_90 = float(values[10].text)
        goals = int(values[11].text) 
        assists = int(values[12].text)
        non_penalty_goals = int(values[13].text)
        penalty_goals = int(values[14].text)
        penalty_attempted = int(values[15].text)
        yellow_cards = int(values[16].text)
        red_card = int(values[17].text)
        goals_per_90 = float(values[18].text)
        assits_per_90 = float(values[19].text)
        non_penalty_goals_per_90 = float(values[20].text)

        # stats.append([index, name, country, position, club, league, games_played, games_started, minutes_played, minutes_per_90, goals, assists, non_penalty_goals, penalty_goals, penalty_attempted, yellow_cards, red_card, goals_per_90, assits_per_90, non_penalty_goals_per_90])
        
        stats = [player_id, name, country, position, club, league, games_played, games_started,\
                                minutes_played, minutes_per_90, goals, assists, non_penalty_goals, penalty_goals,\
                                penalty_attempted, yellow_cards, red_card, goals_per_90, assits_per_90,\
                                non_penalty_goals_per_90]
#         pd.DataFrame([stats], columns=cols).head()
#         df = df.append(pd.DataFrame([stats], columns=cols))
#         df = pd.conca([df, pd.DataFrame([index, name, country, position, club, league, games_played, games_started, minutes_played, minutes_per_90, goals, assists, non_penalty_goals, penalty_goals, penalty_attempted, yellow_cards, red_card, goals_per_90, assits_per_90, non_penalty_goals_per_90])], axis=0, ignore_index = True)
        df = pd.concat([df, pd.DataFrame([stats], columns=cols)])
    
    
df = df.set_index('player_id')
# df.to_csv("data.csv")
df.head()
df.shape

(2383, 19)

In [28]:
#one hot encoding position
mlb = MultiLabelBinarizer(sparse_output = True)
df = df.join(
            pd.DataFrame.sparse.from_spmatrix(
                mlb.fit_transform(df.pop('position')),
                index=df.index,
                columns=mlb.classes_))

In [29]:
df.to_csv("data.csv")

In [35]:
temp = df[['name', 'GK', 'DF', 'MF', 'FW']][0:20]
temp.head(20)

                        name  GK  DF  MF  FW
player_id
1           Brenden Aaronson   0   0   1   1
2           Yunis Abdelhamid   0   1   0   0
3              Himad Abdelli   0   0   1   1
4          Salis Abdul Samed   0   0   1   0
5            Laurent Abergel   0   0   1   0
6             Matthis Abline   0   0   1   1
7          Zakaria Aboukhlal   0   0   1   1
8              Tammy Abraham   0   0   0   1
9           Francesco Acerbi   0   1   0   0
10              Mohamed Achi   0   0   0   1
11              Marcos Acu√±a   0   1   0   0
12                 Che Adams   0   0   0   1
13               Tyler Adams   0   0   1   0
14            Sargis Adamyan   0   0   1   1
15          Tosin Adarabioyo   0   1   0   0
16            Martin Adeline   0   0   1   1
17             Karim Adeyemi   0   0   1   1
18                Amine Adli   0   0   0   1
19               Yacine Adli   0   0   1   1
20          Michel Aebischer   0   0   1   1

In [68]:
player_id = 19
player = temp.iloc[player_id]
print(player)
temp[['GK', 'DF', 'MF', 'FW']].head()
player[["GK", "DF", "MF", "FW"]].head()
dot_product = temp[['GK', 'DF', 'MF', 'FW']].dot(player[["GK", "DF", "MF", "FW"]])
dot_product.rename("similarity")
temp['similarity'] = dot_product
temp.head(20)

name          Michel Aebischer
GK                           0
DF                           0
MF                           1
FW                           1
similarity                   2
Name: 20, dtype: Sparse[object, 0]

                        name  GK  DF  MF  FW similarity
player_id
1           Brenden Aaronson   0   0   1   1          2
2           Yunis Abdelhamid   0   1   0   0          0
3              Himad Abdelli   0   0   1   1          2
4          Salis Abdul Samed   0   0   1   0          1
5            Laurent Abergel   0   0   1   0          1
6             Matthis Abline   0   0   1   1          2
7          Zakaria Aboukhlal   0   0   1   1          2
8              Tammy Abraham   0   0   0   1          1
9           Francesco Acerbi   0   1   0   0          0
10              Mohamed Achi   0   0   0   1          1
11              Marcos Acu√±a   0   1   0   0          0
12                 Che Adams   0   0   0   1          1
13               Tyler Adams   0   0   1   0          1
14            Sargis Adamyan   0   0   1   1          2
15          Tosin Adarabioyo   0   1   0   0          0
16            Martin Adeline   0   0   1   1          2
17             Karim Adeyemi   0   0   1   1          2
18                Amine Adli   0   0   0   1          1
19               Yacine Adli   0   0   1   1          2
20          Michel Aebischer   0   0   1   1          2

,name,country,club,league,games_played,games_started,minutes_played,minutes_per_90,goals,assists,...,penalty_attempted,yellow_cards,red_card,goals_per_90,assits_per_90,non_penalty_goals_per_90,DF,FW,GK,MF
player_id,,,,,,,,,,,,,,,,,,,,,
1,Brenden Aaronson,USA,Leeds United,Premier League,14,14,1189,13.2,1,2,...,0,2,0,0.08,0.15,0.23,0,1,0,1
2,Yunis Abdelhamid,MAR,Reims,Ligue 1,15,15,1350,15.0,0,0,...,0,1,0,0.00,0.00,0.00,1,0,0,0
3,Himad Abdelli,FRA,Angers,Ligue 1,7,2,231,2.6,0,0,...,0,0,0,0.00,0.00,0.00,0,1,0,1
4,Salis Abdul Samed,GHA,Lens,Ligue 1,15,15,1349,15.0,1,0,...,0,2,0,0.07,0.00,0.07,0,0,0,1
5,Laurent Abergel,FRA,Lorient,Ligue 1,10,10,807,9.0,0,1,...,0,2,0,0.00,0.11,0.11,0,0,0,1

In [69]:
def recommend_player(player_id):
    player = df.iloc[player_id-1]